### ISSUE TITLE
Bindings for Rust

### ISSUE THREAD

**Issue by farooqkz** [rsharifnasab/DJ#5]
Hello.
How can I use DJ as a library from Rust?

**Comment by rsharifnasab** [comment]
This project does not intend to be a library, instead, it is a standalone project that you can compile and run. Interacting with the student codes are solely with bash scripts, and it doesn't need any FFI or binding at all; this means that it can judge rust codes as well as other languages. Check out the `examples` dir for some working examples of compile scripts.

**Comment by farooqkz** [comment]
@rsharifnasab Thanks for the explanation, my friend. However, you had to close this issue as "Invalid/won't fix" rather than completed :)
